name= input ("Enter your name: ")
print ("hello" + name + "!" )
age= input ("Enter your age: ")
print ("hello" + name + "! You are " + age )
name= input ("Enter your name: ")
age= input ("Enter your age: ")
print ("hello" + name + "! You are " + age )